# Generated by Django 5.2.17 on 2026-08-12 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("claimed_year", models.CharField(blank=True, max_length=20)),
                (
                    "asking_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("seller_platform", models.CharField(blank=True, max_length=100)),
                ("listing_url", models.URLField(blank=True)),
                ("listing_text", models.TextField(blank=True)),
                ("seller_claims", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready_for_payment", "Ready for payment"),
                            ("paid", "Paid"),
                            ("analyzing", "Analyzing"),
                            ("complete", "Complete"),
                            ("error", "Error"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
