# Generated by Django 5.2.17 on 2026-08-12 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.ImageField(upload_to="case-images/%Y/%m/%d/")),
                (
                    "claimed_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dial", "Dial"),
                            ("rehaut", "Rehaut"),
                            ("date_cyclops", "Date / cyclops"),
                            ("bezel", "Bezel"),
                            ("crown_guards", "Crown guards"),
                            ("caseback", "Caseback"),
                            ("bracelet", "Bracelet"),
                            ("clasp", "Clasp"),
                            ("end_links", "End links"),
                            ("movement", "Movement"),
                            ("papers", "Papers"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("detected_type", models.CharField(blank=True, max_length=50)),
                ("quality_score", models.FloatField(blank=True, null=True)),
                ("usable", models.BooleanField(default=True)),
                ("analysis_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="cases.watchcase",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
