apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: watchrisk-web
spec:
  template:
    spec:
      containers:
        - image: gcr.io/PROJECT_ID/watchrisk-web
          ports:
            - containerPort: 8080
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: config.settings.production
