# Generated by Django 5.2.17 on 2026-08-12 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("risk_level", models.CharField(max_length=50)),
                ("confidence", models.CharField(max_length=50)),
                ("report_json", models.JSONField(default=dict)),
                ("report_text", models.TextField(blank=True)),
                ("raw_model_output", models.JSONField(blank=True, default=dict)),
                ("model_used", models.CharField(max_length=100)),
                ("prompt_version", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="cases.watchcase",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
